package za.ac.cput.domain;

public enum Permission {
    VIEW_ANONYMIZED_ANALYTICS,
    UPDATE_CATEGORY,
    CREATE_CATEGORY,
    DELETE_CATEGORY,
    UPDATE_USER,
    VIEW_USER,
    UPDATE_USER_PASSWORD,
    DEACTIVATE_USER
}
